defaults:
  - /benchmark/nav/objectnav: objectnav_mp3d
  - _self_


habitat:
  env_task: CleanGymHabitatEnv

  dataset:
    split: val
    data_path: ../data/datasets/objectnav/mp3d/{split}/{split}.json.gz
    scenes_dir: ../data/scene_datasets/


  simulator:
    type: "Sim-v0"
    scene_dataset: ../data/scene_datasets/mp3d/mp3d.scene_dataset_config.json

    habitat_sim_v0:
        physics_config_file: ../data/default.physics_config.json
